### ISSUE TITLE
Blog is down

### ISSUE THREAD

**Issue by alystair** [whatwg/blog.whatwg.org#12]
Pinging @annevk @domenic. Unsure of how critical it is, but I was linked to it via [MDN notes section](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/focus) and discovered it's down. Unsure of downtime duration.

> We encountered an error when trying to load your application and your page could not be served. Check the logs for your application in the App Platform dashboard.

**Comment by annevk** [comment]
Thanks for taking the time to alert us, we're tracking this in https://github.com/whatwg/misc-server/issues/163.
